project/
├── models/Schema
│   ├── user.js            # User schema and model
│   ├── product.js         # Product schema and model
│   └── order.js           # Order schema and model
├── routes/
│   ├── users.js           # Routes for user-related operations
│   ├── products.js        # Routes for product-related operations
│   └── orders.js          # Routes for order-related operations
├── .env                   # Environment variables (MongoDB URI, etc.)
├── index.js               # Main server file
├── package.json           # Project metadata and dependencies
└── package-lock.json      # Auto-generated by npm
